### ISSUE TITLE
Transpile to ES5 in npm prepublish

### ISSUE THREAD

**Issue by vjpr** [fand/EventEmitterDecorator#1]
Even though I use ES7 with the babel require hook for development, when publishing I transpile to ES5. When I try to use your lib I have to bring in the require hook which I don't want to do.

**Comment by fand** [comment]
Oh I didnt know `prepublish` can help us
I'll try it :horse_racing: thx!!

**Comment by fand** [comment]
Now this repo transpiles codes to `lib` in [prepublish](https://github.com/fand/EventEmitterDecorator/blob/master/package.json#L42), and publishes `lib` as specified in [package.json](https://github.com/fand/EventEmitterDecorator/blob/master/package.json#L23).
